### PR TITLE
hk instead of heroku command

### PR DESCRIPTION
**Pull request by koenpunt**
[hk](https://github.com/heroku/hk) is a standalone heroku toolbelt implementation in Go, which makes it faster; both for installation and running.

I tried to test this is by updating my `wercker.yml` with the following:

```yaml
deploy:
  steps:
    - koen/heroku-deploy:
        key-name: HEROKU_DEPLOY_KEY
        run: bin/rake db:migrate
```

But that didn't work, so I don't know how to test this..

### CODE REVIEW

**Comment by hatchan** [comment]
Unfortunately `hk` is not backwards compatible with the current toolbelt. Some users execute commands using the Heroku toolbelt after installing it using this step.

**Comment by koenpunt** [comment]
what of the `hk run` or `heroku run` would be incompatible? Because afaik `run` simply executes the command with heroku's environment variables

**Comment by koenpunt** [comment]
Oh wait, I understand, you mean some users actually depend on the `heroku` command installed by the post install step. That would be bad practice in my opinion, but I understand you don't want to break those usages.

**Comment by hatchan** [comment]
Yeah, and I agree it is bad practise. Unfortunately we've backed into that corner. 

If you still want to use hk than I recommend publishing it on your own account. 

We are looking at creating a new step, which will be a greenfield step, so we won't have these backwards incompatibilities.

**Pull request closed without merging**
